### PR TITLE
BLE_GattServer_AddService: correct _heartrate_value

### PR DESCRIPTION
**Pull request by jeromecoutant**
Hi

hrmCounter is uint16_t in
connectivity/FEATURE_BLE/include/ble/services/HeartRateService.h

I also updated values range to match ST BLE Profile application

### CODE REVIEW

**Comment by paul-szczepanek-arm** [comment]
Thanks. All PRs must target branch development.

**Comment by jeromecoutant** [comment]
Please rebase this development branch....

**Comment by paul-szczepanek-arm** [comment]
OK, I can do it for you but I can't write to your fork so I'll have to make my own PR.

**Comment by paul-szczepanek-arm** [comment]
closing as rebased here: https://github.com/ARMmbed/mbed-os-example-ble/pull/374

**Pull request closed without merging**
