### PR TITLE
Add CMakelists

### PR DESCRIPTION
**Pull request by 0xc0170**
The CMake support is still in development. For more information, see mbed-os/cmake/README.md

Following ARMmbed/mbed-os#13566

### CODE REVIEW

**Comment by pan-** [comment]
Thanks @0xc0170 I changed the base branch to development. I suppose we have to wait for https://github.com/ARMmbed/mbed-os/pull/13566 to be merged ?

**Comment by 0xc0170** [comment]
I need to fix all other example PRs (all were to master). I'll get back to this, to provide step by step how to integrate. My initial proposal was to get first the examples in and test them via Mbed OS PR 13566 (unblocking it).

**Comment by 0xc0170** [comment]
> Thanks @0xc0170 I changed the base branch to development. I suppose we have to wait for ARMmbed/mbed-os#13566 to be merged ?

It was merged. I rebased feature-cmake with development, it should be up to date.

This is ready for integration (please squash merge, 1 commit for this simple change).

**Comment by paul-szczepanek-arm** [comment]
BLE_LED does not exist anymore, if you just rename BLE_LED to BLE_Advertising it should be fine.

**Comment by paul-szczepanek-arm** [comment]
Actually, let me do that.

**Comment by 0xc0170** [comment]
Thanks ! I've just noticed the comment :) lets wait for green light

**Pull request merged**
