### PR TITLE
Fix Typo: From BatteryDemo to ButtonDemo

### PR DESCRIPTION
**Pull request by bestony**
Fix some typo in Button Demo.

### CODE REVIEW

**Comment by pan-** [comment]
Thanks for the submission, the following lines must be updated: 

https://github.com/ARMmbed/mbed-os-example-ble/blob/d2e0dd5458b6073aba92dcd8889c90d71b109021/BLE_Button/source/main.cpp#L64-L65

**Comment by bestony** [comment]
@pan-  updated .

**Comment by bestony** [comment]
what should i do , if i want to build it on the Mbed OS online Compiler?

I think i should

**Comment by pan-** [comment]
@bestony You can test this PR locally and before merging we try it.

**Pull request closed without merging**
