### PR TITLE
Add EP_Agora config in Json file

### PR DESCRIPTION
**Pull request by deepikabhavnani**
Agora board was added in https://github.com/ARMmbed/mbed-os/pull/10629

PR to be merged after mbed-os.lib is updated to release version 5.13.1 or later

### CODE REVIEW

**Comment by maclobdell** [comment]
Can these configs be handled in targets.json?

**Comment by deepikabhavnani** [comment]
> Can these configs be handled in targets.json?

Yes can be

**Comment by maclobdell** [comment]
@ARMmbed/team-embeddedplanet  Please take a look at these configuration options to enable the BLE stack on Agora.  It seems more efficient to add these for your target by default in targets.json.  Please evaluate and make a PR if that makes sense to you.

**Comment by deepikabhavnani** [comment]
@maclobdell  - I checked the targets.json, EP_AGORA inherits from `MCU_NRF52840` and it has correct configs set already https://github.com/ARMmbed/mbed-os/blob/master/targets/targets.json#L7253 in master branch.

Example instead should be updated to latest release.

**Pull request closed without merging**
